baseURL = "https://remilarius.github.io/Anthology/"
languageCode = "en-us"
title = "Hugo Site"
theme = "dimension"
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "public"

[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]
